---
#
# Ansible managed
#
repository:
  description: Install gimp on your system.
  homepage: https://buluma.github.io/
  topics: vim, server, sudo, system, ansible, molecule, tox, playbook, hacktoberfest
